(eval-when (:compile-toplevel :load-toplevel :execute)
  (declaim (optimize (debug 3))))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload :cl-irc))

(defun test ()
  (flet ((message-received-hook (message)
	   (format t "HALP~%")
	   ;(format t "message received: ~A~%" message)
	   ))
    (let ((connection (irc:connect :nickname "lispbot" :server "irc.cat.pdx.edu")))
      (irc:join connection "#bots")
      (irc:add-hook connection 'irc-message-event #'message-received-hook)
      (irc:add-hook connection 'dcc-message-event #'message-received-hook)
      (irc:add-hook connection 'default-event #'message-received-hook)
      (irc:read-message-loop connection))))
